Repository DOSOPT-CDS-TABLING/Tabling-iOS, pull requests merged in 2023-11, with the labels that each got.

#2 [Feat] #1 - 프로젝트 세팅
  Tabling-iOS/Tabling-iOS.xcodeproj/project.pbxproj
  Tabling-iOS/Tabling-iOS/Application/AppDelegate.swift
  Tabling-iOS/Tabling-iOS/Application/SceneDelegate.swift
  Tabling-iOS/Tabling-iOS/ExampleCollectionViewCell.swift
  Tabling-iOS/Tabling-iOS/Global/Extension/NSObject+.swift
  Tabling-iOS/Tabling-iOS/Global/Extension/UIColor+.swift
  Tabling-iOS/Tabling-iOS/Global/Extension/UIImage+.swift
  Tabling-iOS/Tabling-iOS/Global/Extension/UILabel+.swift
  Tabling-iOS/Tabling-iOS/Global/Extension/UIView+.swift
  Tabling-iOS/Tabling-iOS/Global/Literals/ColorLiterals.swift
  Tabling-iOS/Tabling-iOS/Global/Literals/FontLiterals.swift
  Tabling-iOS/Tabling-iOS/Global/Literals/ImageLiterals.swift
  Tabling-iOS/Tabling-iOS/Global/Literals/StringLiterals.swift
  Tabling-iOS/Tabling-iOS/Global/Protocols/UICollectionViewRegisterable.swift
  Tabling-iOS/Tabling-iOS/Global/Protocols/UITableViewRegisterable.swift
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/logo.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/Contents.json
  Tabling-iOS/Tabling-iOS/Global/Resources/Font/Pretendard-Regular.otf
  Tabling-iOS/Tabling-iOS/Global/Resources/Font/Pretendard-SemiBold.otf
  Tabling-iOS/Tabling-iOS/Global/Supporting Files/Base.lproj/LaunchScreen.storyboard
  Tabling-iOS/Tabling-iOS/Info.plist
  Tabling-iOS/Tabling-iOS/Network/Entity/StoreDetail/StoreDetailEntity.swift
  Tabling-iOS/Tabling-iOS/Network/Entity/StoreList/StoreListEntity.swift
  Tabling-iOS/Tabling-iOS/Network/Entity/TablingList/TablingListEntity.swift
  Tabling-iOS/Tabling-iOS/Network/Entity/WaitingDetail/WaitingDetailEntity.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/StoreDetailView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/ViewController/StoreDetailViewController.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreList/View/StoreListView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreList/ViewController/StoreListViewController.swift
  Tabling-iOS/Tabling-iOS/Presentation/TablingList/View/TablingListView.swift
  Tabling-iOS/Tabling-iOS/Presentation/TablingList/ViewController/TablingListViewController.swift
  Tabling-iOS/Tabling-iOS/Presentation/WaitingDetail/View/WaitingDetailView.swift
  Tabling-iOS/Tabling-iOS/Presentation/WaitingDetail/ViewController/WaitingDetailViewController.swift
  Tabling-iOS/Tabling-iOS/View.swift
  Tabling-iOS/Tabling-iOS/ViewController.swift
Labels: ⚙️Setting, 🦖아라

#5 [Add] #3 - Swiftlint 적용, README 추가
  README.md
  Tabling-iOS/.swiftlint.yml
  Tabling-iOS/Tabling-iOS.xcodeproj/project.pbxproj
  Tabling-iOS/Tabling-iOS/Global/Extension/UILabel+.swift
  Tabling-iOS/Tabling-iOS/Global/Literals/FontLiterals.swift
  Tabling-iOS/Tabling-iOS/Global/Protocols/UICollectionViewRegisterable.swift
Labels: 📦Add, 🐻‍❄️민재

#8 [Fix] #7 - 폰트 설정 수정
  README.md
  Tabling-iOS/Tabling-iOS/Global/Extension/UILabel+.swift
  Tabling-iOS/Tabling-iOS/Info.plist
  Tabling-iOS/Tabling-iOS/ViewController.swift
Labels: 🦖아라, ⚒️Fix

#12 [Feat] #10 - 원격줄서기 완료 팝업 뷰 구현
  Tabling-iOS/Tabling-iOS.xcodeproj/project.pbxproj
  Tabling-iOS/Tabling-iOS/Global/Extension/UILabel+.swift
  Tabling-iOS/Tabling-iOS/Global/Literals/ColorLiterals.swift
  Tabling-iOS/Tabling-iOS/Global/Literals/StringLiterals.swift
  Tabling-iOS/Tabling-iOS/Network/Entity/StoreDetail/ReserveEntity.swift
  Tabling-iOS/Tabling-iOS/Presentation/ReserveAlert/View/ReserveAlertView.swift
  Tabling-iOS/Tabling-iOS/Presentation/ReserveAlert/ViewController/ReserveAlertViewController.swift
Labels: ✨Feat, 🎨UI, 🦖아라

#11 [Feat] #9 - 매장 상세 뷰 구현
  Tabling-iOS/Tabling-iOS.xcodeproj/project.pbxproj
  Tabling-iOS/Tabling-iOS/Application/SceneDelegate.swift
  Tabling-iOS/Tabling-iOS/Global/Extension/UILabel+.swift
  Tabling-iOS/Tabling-iOS/Global/Extension/UIStackView+.swift
  Tabling-iOS/Tabling-iOS/Global/Literals/StringLiterals.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/AllMenuView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/HomeView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/RecentReviewView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/StoreDetailBottomTabView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/StoreDetailView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/StoreDetatilImageScrollView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/ViewController/StoreDetailViewController.swift
Labels: ✨Feat, 🎨UI, 🐻‍❄️민재

#16 [Feat] #13 - 방문 인원 선택 바텀 시트 구현
  Tabling-iOS/.swiftlint.yml
  Tabling-iOS/Tabling-iOS.xcodeproj/project.pbxproj
  Tabling-iOS/Tabling-iOS/Global/Extension/UILabel+.swift
  Tabling-iOS/Tabling-iOS/Global/Literals/ImageLiterals.swift
  Tabling-iOS/Tabling-iOS/Global/Literals/StringLiterals.swift
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/ic_minus_able.imageset/Contents.json
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/ic_minus_able.imageset/ic_minus.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/ic_minus_able.imageset/ic_minus@2x.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/ic_minus_able.imageset/ic_minus@3x.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/ic_minus_disable.imageset/Contents.json
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/ic_minus_disable.imageset/ic_minus.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/ic_minus_disable.imageset/ic_minus@2x.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/ic_minus_disable.imageset/ic_minus@3x.png
  Tabling-iOS/Tabling-iOS/Presentation/ReserveBottomSheet/View/ReserveBottomSheetView.swift
  Tabling-iOS/Tabling-iOS/Presentation/ReserveBottomSheet/ViewController/ReserveBottomSheetViewController.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/StoreDetailBottomTabView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/StoreDetailView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/ViewController/StoreDetailViewController.swift
Labels: ✨Feat, 🎨UI, 🐻‍❄️민재

#18 [Feat] #17 - 전체 메뉴 Compositional Layout 뷰 구현
  Tabling-iOS/Tabling-iOS.xcodeproj/project.pbxproj
  Tabling-iOS/Tabling-iOS/Global/Literals/ImageLiterals.swift
  Tabling-iOS/Tabling-iOS/Global/Literals/StringLiterals.swift
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/btn_all_menu_look.imageset/Contents.json
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/btn_all_menu_look.imageset/btn_normal.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/btn_all_menu_look.imageset/btn_normal@2x.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/btn_all_menu_look.imageset/btn_normal@3x.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/examplePhoto.imageset/Contents.json
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/examplePhoto.imageset/Rectangle 41971.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/examplePhoto.imageset/Rectangle 41971@2x.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/examplePhoto.imageset/Rectangle 41971@3x.png
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/MenuCollectionHeaderView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/MenuCollectionViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/AllMenuView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/StoreDetailView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/ViewController/StoreDetailViewController.swift
Labels: ✨Feat, 🎨UI, 🐻‍❄️민재

#19 [Feat] #14 - 원격줄서기내역 뷰 구현
  Tabling-iOS/Tabling-iOS.xcodeproj/project.pbxproj
  Tabling-iOS/Tabling-iOS/Global/Extension/UILabel+.swift
  Tabling-iOS/Tabling-iOS/Global/Literals/ColorLiterals.swift
  Tabling-iOS/Tabling-iOS/Global/Literals/StringLiterals.swift
  Tabling-iOS/Tabling-iOS/Network/Entity/TablingList/TablingListEntity.swift
  Tabling-iOS/Tabling-iOS/Presentation/TablingList/Cell/CompleteCollectionViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/TablingList/View/CancelCollectionView.swift
  Tabling-iOS/Tabling-iOS/Presentation/TablingList/View/CompleteCollectionView.swift
  Tabling-iOS/Tabling-iOS/Presentation/TablingList/View/TablingListView.swift
  Tabling-iOS/Tabling-iOS/Presentation/TablingList/ViewController/TablingListViewController.swift
Labels: ✨Feat, 🎨UI, 🦖아라

#22 [Feat] #20 - 매장상세 리뷰 뷰 구현
  Tabling-iOS/Tabling-iOS.xcodeproj/project.pbxproj
  Tabling-iOS/Tabling-iOS/Global/Literals/StringLiterals.swift
  Tabling-iOS/Tabling-iOS/Network/Entity/StoreDetail/StoreDetailEntity.swift
  Tabling-iOS/Tabling-iOS/Presentation/ReserveAlert/ViewController/ReserveAlertViewController.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/DetailStarTableViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/RecentReviewTableViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/RecentReviewView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/StoreDetailView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/ViewController/StoreDetailViewController.swift
  Tabling-iOS/Tabling-iOS/Presentation/TablingList/ViewController/TablingListViewController.swift
Labels: ✨Feat, 🎨UI, 🦖아라

#24 [Setting] #23 - 네트워크 세팅
  Tabling-iOS/Tabling-iOS.xcodeproj/project.pbxproj
  Tabling-iOS/Tabling-iOS/Info.plist
  Tabling-iOS/Tabling-iOS/Network/Base/BaseService.swift
  Tabling-iOS/Tabling-iOS/Network/Base/GenericResponse.swift
  Tabling-iOS/Tabling-iOS/Network/Base/NetworkConstant.swift
  Tabling-iOS/Tabling-iOS/Network/Base/NetworkResult.swift
  Tabling-iOS/Tabling-iOS/Network/Base/URLConstant.swift
  Tabling-iOS/Tabling-iOS/Network/Entity/TablingList/TablingListEntity.swift
  Tabling-iOS/Tabling-iOS/Network/Enviornment/Config.swift
  Tabling-iOS/Tabling-iOS/Network/Services/StoreDetailService.swift
  Tabling-iOS/Tabling-iOS/Network/Services/StoreListService.swift
  Tabling-iOS/Tabling-iOS/Network/Services/TablingListService.swift
  Tabling-iOS/Tabling-iOS/Network/Services/WaitingDetailService.swift
  Tabling-iOS/Tabling-iOS/Presentation/TablingList/ViewController/TablingListViewController.swift
Labels: ⚙️Setting, 🌎Network, 🦖아라

#28 [Feat] #21 - 매장 상세 뷰 버그 해결
  Tabling-iOS/Tabling-iOS.xcodeproj/project.pbxproj
  Tabling-iOS/Tabling-iOS/Global/Literals/ImageLiterals.swift
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/big_1.imageset/Contents.json
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/big_1.imageset/big_1.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/big_1.imageset/big_1@2x.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/big_1.imageset/big_1@3x.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/big_2.imageset/Contents.json
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/big_2.imageset/big_2.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/big_2.imageset/big_2@2x.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/big_2.imageset/big_2@3x.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/btn_all_review_look.imageset/Contents.json
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/btn_all_review_look.imageset/btn_normal.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/btn_all_review_look.imageset/btn_normal@2x.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/btn_all_review_look.imageset/btn_normal@3x.png
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/MenuCollectionViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/StoreDetailImageCollectionViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/AllMenuView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/ImageScrollCollectionView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/RecentReviewView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/StoreDetailView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/StoreDetatilImageScrollView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/ViewController/StoreDetailViewController.swift
Labels: ✨Feat, 🎨UI, 🐻‍❄️민재

#34 [Feat] #33 - 대기 상세 뷰 구현
  Tabling-iOS/Tabling-iOS.xcodeproj/project.pbxproj
  Tabling-iOS/Tabling-iOS/Global/Extension/UILabel+.swift
  Tabling-iOS/Tabling-iOS/Global/Literals/ImageLiterals.swift
  Tabling-iOS/Tabling-iOS/Global/Literals/StringLiterals.swift
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/ic_more_bc.imageset/Contents.json
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/ic_more_bc.imageset/ic_more_bc.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/ic_more_bc.imageset/ic_more_bc@2x.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/ic_more_bc.imageset/ic_more_bc@3x.png
  Tabling-iOS/Tabling-iOS/Network/Entity/StoreList/LocationData.swift
  Tabling-iOS/Tabling-iOS/Network/Entity/StoreList/StoreListEntity.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/StoreTagCollectionViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/HomeView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/StoreTagCollectionView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreList/Cell/LocationCollectionViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreList/Cell/StoreListCollectionHeaderView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreList/Cell/StoreListCollectionViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreList/View/LocationCollectionView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreList/View/StoreListCollectionView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreList/ViewController/StoreListViewController.swift
  Tabling-iOS/Tabling-iOS/Presentation/WaitingDetail/ViewController/WaitingDetailViewController.swift
Labels: ✨Feat, 🎨UI, 🐰연수

#37 [Feat] #36 - 지역인기매장 뷰 API 구현
  Tabling-iOS/Tabling-iOS/Global/Extension/UIImage+.swift
  Tabling-iOS/Tabling-iOS/Network/Base/URLConstant.swift
  Tabling-iOS/Tabling-iOS/Network/Entity/StoreList/StoreListEntity.swift
  Tabling-iOS/Tabling-iOS/Network/Services/StoreListService.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreList/Cell/StoreListCollectionViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreList/View/StoreListCollectionView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreList/ViewController/StoreListViewController.swift
Labels: ✨Feat, 🌎Network, 🦖아라

#38 [🎨Chore] #35 - 코드 리뷰 반영
  Tabling-iOS/Tabling-iOS.xcodeproj/project.pbxproj
  Tabling-iOS/Tabling-iOS/Application/SceneDelegate.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/LeftAlignedCollectionViewFlowLayout.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/StoreTagCollectionViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/HomeView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/StoreTagCollectionView.swift
Labels: 🎨UI, 🐰연수, ⚒️Fix

#40 [✨Feat] #39 - 대기 상세 뷰 API 연동
  Tabling-iOS/Tabling-iOS.xcodeproj/project.pbxproj
  Tabling-iOS/Tabling-iOS/Application/SceneDelegate.swift
  Tabling-iOS/Tabling-iOS/Network/Base/URLConstant.swift
  Tabling-iOS/Tabling-iOS/Network/Entity/WaitingDetail/WaitingDetailEntity.swift
  Tabling-iOS/Tabling-iOS/Network/Services/WaitingDetailService.swift
  Tabling-iOS/Tabling-iOS/Presentation/TablingList/Cell/CompleteCollectionViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/TablingList/ViewController/TablingListViewController.swift
  Tabling-iOS/Tabling-iOS/Presentation/WaitingDetail/View/WaitingDetailView.swift
  Tabling-iOS/Tabling-iOS/Presentation/WaitingDetail/ViewController/WaitingDetailViewController.swift
Labels: ✨Feat, 🌎Network, 🐰연수

#43 [Feat] #29 - 매장 상세 뷰 서버 연결
  Tabling-iOS/Tabling-iOS.xcodeproj/project.pbxproj
  Tabling-iOS/Tabling-iOS/Application/SceneDelegate.swift
  Tabling-iOS/Tabling-iOS/Global/Extension/UIImage+.swift
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/big_1.imageset/Contents.json
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/big_1.imageset/big_1.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/big_1.imageset/big_1@2x.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/big_1.imageset/big_1@3x.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/big_2.imageset/Contents.json
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/big_2.imageset/big_2.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/big_2.imageset/big_2@2x.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/big_2.imageset/big_2@3x.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/examplePhoto.imageset/Contents.json
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/examplePhoto.imageset/Rectangle 41971.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/examplePhoto.imageset/Rectangle 41971@2x.png
  Tabling-iOS/Tabling-iOS/Global/Resources/Assets.xcassets/examplePhoto.imageset/Rectangle 41971@3x.png
  Tabling-iOS/Tabling-iOS/Info.plist
  Tabling-iOS/Tabling-iOS/Network/Base/URLConstant.swift
  Tabling-iOS/Tabling-iOS/Network/Entity/StoreDetail/StoreDetailEntity.swift
  Tabling-iOS/Tabling-iOS/Network/Services/StoreDetailService.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/LeftAlignedCollectionViewFlowLayout.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/MenuCollectionHeaderView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/MenuCollectionViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/StoreDetailImageCollectionViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/StoreTagCollectionViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/AllMenuView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/HomeView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/ImageScrollCollectionView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/RecentReviewView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/StoreDetailView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/StoreTagCollectionView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/ViewController/StoreDetailViewController.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreList/ViewController/StoreListViewController.swift
Labels: ✨Feat, 🌎Network, 🐻‍❄️민재

#45 [Feat] #44 - 원격줄서기 API 구현
  Tabling-iOS/Tabling-iOS/Application/SceneDelegate.swift
  Tabling-iOS/Tabling-iOS/Global/Literals/StringLiterals.swift
  Tabling-iOS/Tabling-iOS/Network/Entity/StoreDetail/ReserveEntity.swift
  Tabling-iOS/Tabling-iOS/Network/Services/StoreDetailService.swift
  Tabling-iOS/Tabling-iOS/Presentation/ReserveAlert/ViewController/ReserveAlertViewController.swift
  Tabling-iOS/Tabling-iOS/Presentation/ReserveBottomSheet/View/ReserveBottomSheetView.swift
  Tabling-iOS/Tabling-iOS/Presentation/ReserveBottomSheet/ViewController/ReserveBottomSheetViewController.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/DetailStarTableViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/LeftAlignedCollectionViewFlowLayout.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/MenuCollectionHeaderView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/RecentReviewTableViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/Cell/StoreTagCollectionViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/AllMenuView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/HomeView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/RecentReviewView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/StoreDetailView.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/ViewController/StoreDetailViewController.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreList/Cell/StoreListCollectionViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/TablingList/Cell/CompleteCollectionViewCell.swift
  Tabling-iOS/Tabling-iOS/Presentation/TablingList/View/TablingListView.swift
Labels: ✨Feat, 🌎Network, 🦖아라

#46 [✨Feat] #41 - 대기 상세 이용 상태에 따른 분기 처리
  Tabling-iOS/Tabling-iOS/Global/Literals/StringLiterals.swift
  Tabling-iOS/Tabling-iOS/Presentation/StoreDetail/View/HomeView.swift
  Tabling-iOS/Tabling-iOS/Presentation/WaitingDetail/View/WaitingDetailView.swift
Labels: 🎨UI, 🐰연수, ⚒️Fix
